### ISSUE TITLE
Avgjøre om vi skal fortsette med Backbone

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/colligator-frontend#10]
På mandag bør vi 
- sjekke om det ser ut som koden til @kyrretl lar seg integrere noenlunde greit i en BackBone-basert modell, eller om det er helt mismatch :boom: 
- avgjøre om vi skal fortsette med Backbone eller ei

**Comment by stianlagstad** [comment]
Backbone funker bra! Vi kjører på.
