### ISSUE TITLE
Feilmeldinger

### ISSUE THREAD

**Issue by stianlagstad** [scriptotek/colligator-frontend#17]
Hvis det er noe feil fra serveren. Vi kan ha en liten database lagra i frontend som vises in that case.

**Comment by danmichaelo** [comment]
Pri 1 er bare å vise en melding. Hvis det er en midlertidig feil med backend nå blir spinneren bare stående og snurre…

Husk også at backend ikke får sendt CORS-headere hvis den kræsjer. Så mangel av CORS-headere må tolkes som "Serveren har et midlertid problem".

PS: Da jeg kom tilbake på jobb i dag virket maskinen fremdeles som den skulle :)
