### ISSUE TITLE
Teste visning av bøker som er del av serier

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/colligator-frontend#20]
Må vise `part_no`, `part_name` (der det finnes) og antakelig `part_of.relationship` `part_of.title`.

Eks: [921510055](http://colligator.biblionaut.net/api/documents?q=921510055)

```
"part_name": "Psychology, human physiology, living creatures, botany, ethics, religion, politics, rhetoric and poetics, music, miscellanea",
      "part_no": "2",
      "part_of": {
        "id": "920831230",
        "isbn": "9004094407",
        "issn": null,
        "relationship": "Inkludert i",
        "title": "Theophrastus of Eresus",
        "vocabulary": "NO-TrBIB",
        "volume": null
      },
      "series": [
        {
          "id": null,
          "title": "Philosophia antiqua",
          "volume": "54:2"
        }
      ],
      "title": "Theophrastus of Eresus sources for his life, writings, thought and influence",
```

---

Eks: [900261889](http://colligator.biblionaut.net/api/documents?q=900261889)

```
      "part_name": "Diseases and the doctor",
      "part_no": "A",
      "part_of": {
        "id": "910312990",
        "isbn": null,
        "issn": null,
        "relationship": "Inkludert i",
        "title": "Science in society",
        "vocabulary": "NO-TrBIB",
        "volume": null
      },
      "title": "Science in society",
```

**Comment by stianlagstad** [comment]
Sjekker du commit a525944?

**Comment by stianlagstad** [comment]
Blir litt tricky pga at part_no er så ulikt. Noen har bare tall, mens andre har "Vol. 5", slik som denne:
index.html#cat/Teknologi/2613

Men det ligger inne nå.

**Comment by danmichaelo** [comment]
Bør vi ha noen kobling mellom bind i samme serie? Eller liste opp "andre bøker i samme serie"? Vi har jo god plass.. Man kan gjøre oppslag på serie-ID slik:

http://colligator.biblionaut.net/api/documents?q=part_of.id:801118662

**Comment by stianlagstad** [comment]
+1 for fremtidig greie. Enkel listevisning under beskrivelsen av boka, kanskje?

**Comment by danmichaelo** [comment]
Lukker denne da
