### ISSUE TITLE
Legge til sidetittel

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/colligator-frontend#23]
som forklarer hvor man er, f.eks. "Samling 42", "Bøker om '{Emneord}'"

**Comment by danmichaelo** [comment]
Holder den åpen inntil vi har info om emneord. Viktig at tittelen sier brukeren noe om hvor hen er.

**Comment by stianlagstad** [comment]
Notes to self:
- Nytt view for header
- Ref til view i route
- Oppdatere view i route handlerne på samme måte som andre views oppdateres

**Comment by danmichaelo** [comment]
Egentlig burde `<title>` i `<head>` også blitt oppdatert – det er selvfølgelig mindre viktig nå, men fiks gjerne hvis det er enkelt (ser for meg at det kanskje ikke er det :))
