### ISSUE TITLE
Legg til visning av utlånsstatus

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/colligator-frontend#27]
Ligger under `holdings.circulation_status` (oppdateres daglig). 

Live-oppdatering kan vi få til etter hvert

**Comment by stianlagstad** [comment]
Lagt inn, men bare for første element i arrayen som er holdings. Hvordan vise det hvis arrayen har flere enn ett element?

**Comment by stianlagstad** [comment]
Glem det - så issue 24 nå

**Comment by danmichaelo** [comment]
Status bør oversettes. Trenger bare tre statuser: "Available" => "Tilgjengelig på hylla", "On loan" => "Utlånt", else "Spør i skranken" eller noe sånt
