### ISSUE TITLE
Legg til hjem-knapp og/eller tilbake-knapp

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/colligator-frontend#30]
Tilbake-knapp må evt. gå tilbake til forrige emneord, ikke forrige posisjon i karusellen.

**Comment by stianlagstad** [comment]
Jeg har prøvd litt forskjellig men har ikke løst det enda. Har stilt et spørsmål her:
http://stackoverflow.com/questions/31290622/go-back-in-backbone-history-to-a-specific-point-based-on-the-url-at-that-time

Én løsning er å bare lagre forrige emneord et sted, og når brukeren klikker "forrige emneord"-knappen så sendes brukeren _fram_ til cat/emneord, altså ikke _tilbake_ i browserhistorien men fram til det emneordet på nytt. Jeg kan gjøre det på den måten i morgen/fredag om jeg ikke får svar på SO.

**Comment by danmichaelo** [comment]
Tror det er like greit å bare sende brukeren _fram_ her. Men da må vi ha en liste over besøkte emneord, ja… .pop()
