### ISSUE TITLE
Mer brukervennlig måte å finne boka på

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/colligator-frontend#34]
Oppfølging av #24 og #27 : Vi bør antakelig lage mer brukervennlige meldinger som gir enkle svar på «Hvor finner jeg boka?». Hvis det f.eks. er et ledig eks. i samling 42 trenger vi ikke vise andre eksemplarer.
Noen mulige svar på spørsmålet:
- «Boka er ikke utlånt og skal stå på hylleplass FA322»
- «Boka er dessverre utlånt. Kontakt skranken for å sette deg på reservasjonsliste.»
- «Dette eksemplaret er utlånt, men det finnes et (ledig) eksemplar i biblioteket en trapp opp. Spør etter FYS 1.2» (hvis holding med sublocation "UREAL")
- «Dette eksemplaret er utlånt, men det finnes et (ledig) eksemplar på Humsam/informatikk/x-biblioteket rett i nærheten»

Merk at jeg allerede filtreres holdings på UBO, så vi får ikke resultater fra andre bibliotek utenfor UBO.

**Comment by stianlagstad** [comment]
Slik som dette?

if (shelving_location === "UREAL SAMLING 42" && circulation_status === "Available") {
    vis bare den boka, grønn tekst, kan hentes der og der
else {
    vis liste med info om hver bok
}

**Comment by danmichaelo** [comment]
Mja, jeg tenkte helst at det uansett bare skulle være ett svar, ikke en liste. Tenker en prioritering ála
1. Samling 42, ikke utlånt
2. UREAL, ikke utlånt
3. UBO, ikke utlånt
4. Utlånt

**Comment by stianlagstad** [comment]
Alright. Fikser i kveld eller i morgen tidlig!
