### ISSUE TITLE
Størrelse på emneordhistorieknappene

### ISSUE THREAD

**Issue by stianlagstad** [scriptotek/colligator-frontend#56]
Om emneordet er for langt så går knappen tilbake til "forrige/neste emneord" over/bak emneordet man er på

**Comment by stianlagstad** [comment]
Litt usikker på hva jeg skal gjøre med det. Se eksempel:

![bilde](http://s2.postimg.org/kqxwl9drt/emneordknapp_for_stor.png).

Noen forslag? Kanskje jeg skal begrense emneordet basert på lengde, slik at "Informatikk i historien og sånt" heller blir "Informatikk i hi..."?

**Comment by danmichaelo** [comment]
Ser ut som overflow ikke settes riktig ved mouseover ;)

<img width="562" alt="skjermbilde 2015-09-03 kl 16 37 08" src="https://cloud.githubusercontent.com/assets/434495/9661849/eeea393e-525c-11e5-9d8c-490c16bec873.png">

**Comment by stianlagstad** [comment]
Blææææææææææææææ :)

**Comment by danmichaelo** [comment]
:laughing:
